name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Build
      run: |
        ./gradlew assembleDebug
    - name: Store generated universal APK file
      uses: actions/upload-artifact@v2
      with:
        name: tentel-app-universal
        path: |
            ./app/build/outputs/apk/debug/tentel-app-universal-debug.apk
            ./app/build/outputs/apk/debug/output-metadata.json
    - name: Store generated arm64-v8a APK file
      uses: actions/upload-artifact@v2
      with:
        name: tentel-app-arm64-v8a
        path: |
          ./app/build/outputs/apk/debug/tentel-app-arm64-v8a-debug.apk
          ./app/build/outputs/apk/debug/output-metadata.json
    - name: Store generated armeabi-v7a APK file
      uses: actions/upload-artifact@v2
      with:
        name: tentel-app-armeabi-v7a
        path: |
          ./app/build/outputs/apk/debug/tentel-app-armeabi-v7a-debug.apk
          ./app/build/outputs/apk/debug/output-metadata.json
    - name: Store generated x86_64 APK file
      uses: actions/upload-artifact@v2
      with:
        name: tentel-app-x86_64
        path: |
          ./app/build/outputs/apk/debug/tentel-app-x86_64-debug.apk
          ./app/build/outputs/apk/debug/output-metadata.json
    - name: Store generated x86 APK file
      uses: actions/upload-artifact@v2
      with:
        name: tentel-app-x86
        path: |
          ./app/build/outputs/apk/debug/tentel-app-x86-debug.apk
          ./app/build/outputs/apk/debug/output-metadata.json
